services:
  db:
    image: postgres:15
    container_name: esp32-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DB_DATA_PATH:-./postgres-data}:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esp32-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DEFAULT_USER_USERNAME: ${APP_DEFAULT_USER_USERNAME:-admin123}
      APP_DEFAULT_USER_PASSWORD: ${APP_DEFAULT_USER_PASSWORD:-321nimda}
    ports:
      - "8080:8080"
